# Future V0.1 交易系统配置文件

# 期权监控器配置
option_monitor:
  # 监控目录（存放待解析的期权数据文件）
  watch_dir: '/Users/niningxi/Documents/WebTextDetail/'
  
  # 持久化目录（存放处理记录和解析结果）
  persistant_dir: '/Users/niningxi/Desktop/future/op_trade_data'

# 系统配置
system:
  # 检查间隔（秒）
  check_interval: 20
  
  # 对账配置
  reconciliation:
    # 对账时间（美东时间，格式：HH:MM:SS）
    time: '17:00:00'
    # 是否自动修复差异（以Futu数据为准）
    auto_fix: true

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: 'INFO'
  
  # 日志文件路径
  log_file: 'logs/trading_system.log'

strategy:
    name: 'v7'
    
    # === 入场过滤器 ===
    filter:
      trade_start_time: "9:30:00"              # 交易开始时间（美东）
      min_option_premium: 100000                # 最小期权溢价（$100K）
      
      # 历史Premium过滤（使用txt文件中的历史数据）
      historical_premium_multiplier: 0        # 历史倍数（当前溢价需>历史均值2倍，0=禁用）
      
      # 做空交易过滤
      max_daily_short_premium: 500000         # 当天做空premium总和上限（$500K，0=禁用）
    
    # === 仓位配置 ===
    position_compute:
      max_daily_trades: 5                       # 每日最大交易次数
      max_daily_position: 0.95                  # 总仓位上限（99%）
      max_single_position: 0.40                 # 单笔仓位上限（40%）
      premium_divisor: 1000000                   # 仓位计算除数
    
    # === 出场配置 ===
    stop_loss: 0.10                          # 止损阈值（-10%，用于动态和静态止损）
    take_profit: 0.20                        # 止盈（+20%）
    
    # 动态止损策略（优先级高于静态止损）
    use_dynamic_stop_loss: true              # 是否启用动态止损策略（相对于最高点）
    dynamic_stop_loss_threshold: 0.05        # 动态止损阈值（从最高点下跌5%时卖出）
    
    holding_days: 6                             # 持仓天数
    exit_time: "15:00:00"                       # 定时退出时间（美东）
    
    # === 黑名单 ===
    blacklist_days: 5                          # 黑名单天数

