# Future V0.1 交易系统配置文件

# 期权监控器配置
option_monitor:
  # 监控目录（存放待解析的期权数据文件）
  watch_dir: '/Users/niningxi/Documents/WebText/'
  
  # 持久化目录（存放处理记录和解析结果）
  persistant_dir: '/Users/niningxi/Desktop/future/op_trade_data'

# 系统配置
system:
  # 检查间隔（秒）
  check_interval: 20
  
  # 对账配置
  reconciliation:
    # 对账时间（美东时间，格式：HH:MM:SS）
    time: '17:00:00'
    # 是否自动修复差异（以Futu数据为准）
    auto_fix: true

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: 'INFO'
  
  # 日志文件路径
  log_file: 'logs/trading_system.log'

strategy:
    name: 'v6'
    filter:
      min_premium_usd: 100000
      entry_time_et: "15:30:00"
      max_trade_time: 5
      max_position: 0.99
    take_profit: 0.15
    stop_loss: 0.05
    holding_days: 6
    # 持仓到期卖出时间（美东时间，格式：HH:MM:SS）
    holding_days_exit_time: "15:00:00"
    # 黑名单天数：过去N个交易日买入过的股票不再买入（避免短期重复交易）
    blacklist_days: 15
    position_compute:
      max_premium_usd: 800000
      max_per_position: 0.3

