# Future V0.1 交易系统配置文件 - V7策略配置
# V7 事件驱动期权流动量策略 - 回测收益率：543.63%

# 期权监控器配置
option_monitor:
  # 监控目录（存放待解析的期权数据文件）
  watch_dir: '/Users/niningxi/Documents/WebText/'
  
  # 持久化目录（存放处理记录和解析结果）
  persistant_dir: '/Users/niningxi/Desktop/future/op_trade_data'

# 系统配置
system:
  # 检查间隔（秒）
  check_interval: 20
  
  # 对账配置
  reconciliation:
    # 对账时间（美东时间，格式：HH:MM:SS）
    time: '17:00:00'
    # 是否自动修复差异（以Futu数据为准）
    auto_fix: true

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: 'INFO'
  
  # 日志文件路径
  log_file: 'logs/trading_system_v7.log'

# V7策略配置
strategy:
  name: 'v7'
  
  # ===== 入场过滤条件 =====
  filter:
    # 交易时间窗口（美东时间）
    trade_start_time: '9:00:00'  # 中午12:30 PM之后（ET时间）
    
    # Entry Delay：信号后延迟买入的分钟数
    entry_delay: 1
    
    # 最小期权溢价（美元）
    min_option_premium: 100000  # $100,000
    
    # 距离收盘缓冲时间（分钟）- 15:54之后的信号不交易
    market_close_buffer: 2
    
    # 历史Premium过滤
    historical_premium_multiplier: 0  # 当前溢价必须 >= 历史均值 × 2倍
    historical_lookback_days: 7  # 回溯7天
    # 实盘：'call_csv_files' 或实际路径
    # 回测：'BACKTEST_DISABLE' 禁用策略内部的历史过滤（由回测引擎处理）
    call_csv_dir: 'call_csv_files'
    
    # 做空交易过滤：如果当天做空交易premium总和超过阈值，过滤该信号
    max_daily_short_premium: 200000  # 当天做空premium总和上限（美元），0=禁用此过滤
  
  # ===== 仓位管理 =====
  position_compute:
    max_daily_trades: 5  # 每日最多5笔交易
    max_daily_position: 0.95  # 每日总仓位上限99%
    max_single_position: 0.40  # 单笔仓位上限40%
    premium_divisor: 1000000  # 仓位计算：min(premium/800000, 0.4)
  
  # ===== 杠杆配置 =====
  leverage:
    min_cash_ratio: 0.05  # 最低现金比率1%（不允许杠杆，现金必须>0）
    max_leverage: 0.95  # 最大持仓99%（不使用杠杆）
  
  # ===== 出场条件 =====
  stop_loss: 0.05  # 止损-10%
  take_profit: 0.20  # 止盈+20%
  holding_days: 6  # 持仓天数
  exit_time: '15:00:00'  # 定时退出时间（第N天下午3:00 PM）
  
  # ===== 黑名单 =====
  blacklist_days: 5  # 同一股票15天内不重复交易
  
  # ===== 交易成本 =====
  cost:
    commission_per_share: 0.005  # 每股手续费$0.005
    min_commission: 1.0  # 最低手续费$1
    slippage: 0.001  # 单边滑点0.1%

